module.exports = {
    en: {
        translation: {
            AND: 'and',
            fruit: 'fruit',
            fruit_plural: 'fruits',
            vegetable: 'vegetable',
            vegetable_plural: 'vegetables',
            dryfruit:'dryfruit',
            dryfruit_plural:'dryfruits',
            seafood:'seafood',
            seafood_plural:'seafoods',
            condiment:'condiment',
            condiment_plural:'condiments',
            bakery:'bakery',
            bakery_plural:'bakeries',
            cereal:'cereal',
            cereal_plural:'cereals',
            rice:'rice',
            rice_plural:'rices',
            pasta:'pasta',
            pasta_plural:'pastas',
            pet_care:"pet care",
            pet_care_plural:"pet care",
            baby_care:'baby care', 
            baby_care_plural:'baby care', 
            household_supplies:'household supplies',
            household_supplies_plural:'household supplies',
            health_care:'health care',
            health_care_plural:'health cares',
            personal_care:'personal care',
            personal_care_plural:'personal cares',
            frozen_food:'frozen food',
            frozen_food_plural:'frozen foods',
            baking:'baking',
            baking_plural:'baking',
            beverage:'beverage',
            beverage_plural:'beverages',
            snack:'snack',
            snack_plural:'snacks',
            deli:'deli', 
            deli_plural:'deli', 
            meat:'meat',
            meat_plural:'meats',
            dairy:'dairy',
            dairy_plural:'dairies',
            
            apple: 'apple',
            apple_plural: 'apples',
            banana: 'banana',
            banana_plural: 'bananas',
            orange: 'orange',
            orange_plural: 'oranges',
            mandarin: 'mandarin',
            mandarin_plural: 'mandarins',
            pineapple: 'pineapple',
            pineapple_plural: 'pineapples',
            apricot:'apricot',
            apricot_plural:'apricots',
            avocado:'avocado',
            avocado_plural:'avocados',
            blackberry:'blackberry',
            blackberry_plural:'blackberries',
            blueberry:'blueberry',
            blueberry_plural:'blueberries',
            cherry:'cherry',
            cherry_plural:'cherries',
            coconut:'coconut',
            coconut_plural:'coconuts',
            dragonfruit:'dragonfruit',
            dragonfruit_plural:'dragonfruits',
            grape:'grape',
            grape_plural:'grapes',
            guava:'guava',
            guava_plural:'guavas',
            jackfruit:'jackfruit',
            jackfruit_plural:'jackfruits',
            plum:'plum',
            plum_plural:'plums',
            kiwi:'kiwi',
            kiwi_plural:'kiwis',
            lemon:'lemon',
            lemon_plural:'lemons',
            mango:'mango',
            mango_plural:'mangoes',
            watermelon:'watermelon',
            watermelon_plural:'watermelons',
            mulberry:'mulberry',
            mulberry_plural:'mulberries',
            papaya:'papaya',
            papaya_plural:'papayas',
            peach:'peach',
            peach_plural:'peaches',
            pear:'pear',
            pear_plural:'pears',
            pineberry:'pineberry',
            pineberry_plural:'pineberries',
            rasberry:'rasberry',
            rasberry_plural:'rasberries',
            strawberry:'strawberry',
            strawberry_plural:'strawberries',
            tangerine:'tangerine',
            tangerine_plural:'tangerines',
            muskmelon:'muskmelon',
            muskmelon_plural:'muskmelons',
            
            almond:'almond',
            almond_plural:'almonds',
            pistachio:'pistachio',
            pistachio_plural:'pistachios',
            cashew:'cashew',
            cashew_plural:'cashews',
            date:'date',
            date_plural:'dates',
            hazelnut:'hazelnut',
            hazelnut_plural:'hazelnuts',
            peanut:'peanut',
            peanut_plural:'peanuts',
            betel_nut:'betel nut',
            betel_nut_plural:'betel nuts',
            dry_coconut:'dry coconut',
            dry_coconut_plural:'dry coconuts',
            walnut:'walnut',
            walnut_plural:'walnuts',
            raisin:'raisin',
            raisin_plural:'raisins',
            
            tomato: 'tomato',
            tomato_plural: 'tomatoes',
            carrot: 'carrot',
            carrot_plural: 'carrots',
            pumpkin: 'pumpkin',
            pumpkin_plural: 'pumpkins',
            lettuce: 'lettuce',
            lettuce_plural: 'lettuce',
            cucumber:'cucumber',
            cucumber_plural:'cucumbers',
            beetroot:'beetroot',
            beetroot_plural:'beetroots',
            capsicum:'capsicum',
            capsicum_plural:'capsicums',
            bitter_gourd:'bitter gourd',
            bitter_gourd_plural:'bitter gourds',
            cabbage:'cabbage',
            cabbage_plural:'cabbages',
            cauliflower:'cauliflower',
            cauliflower_plural:'cauliflowers',
            coriander:'coriander',
            coriander_plural:'corianders',
            corn:'corn',
            corn_plural:'corns',
            curry_leaves:'curry leaves',
            curry_leaves_plural:'curry leaves',
            drumstick:'drumstick',
            drumstick_plural:'drumsticks',
            eggplant:'eggplant',
            eggplant_plural:'eggplants',
            fenugreek_leaves:'fenugreek leaves',
            fenugreek_leaves_plural:'fenugreek leaves',
            french_bean:'french bean',
            french_bean_plural:'french beans',
            garlic:'garlic',
            garlic_plural:'garlics',
            ginger:'ginger',
            ginger_plural:'gingers',
            green_chili:'green chili',
            green_chili_plural:'green chilis',
            green_pea:'green pea',
            green_pea_plural:'green peas',
            onion:'onion',
            onion_plural:'onions',
            potato:'potato',
            potato_plural:'potatoes',
            ladyfinger:'ladyfinger',
            ladyfinger_plural:'ladyfingers',
            mustard_leaves:'mustard leaves',
            mustard_leaves_plural:'mustard leaves',
            mushroom:'mushroom',
            mushroom_plural:'mushrooms',
            mint_leaves:'mint leaves',
            mint_leaves_plural:'mint leaves',
            ivy_gourd:'ivy gourd',
            ivy_gourd_plural:'ivy gourds',
            radish:'radish',
            radish_plural:'radishes',
            ridge_gourd:'ridge gourd',
            ridge_gourd_plural:'ridge gourds',
            spinach:'spinach',
            spinach_plural:'spinach',
            sweet_potato:'sweet potato',
            sweet_potato_plural:'sweet potatoes',
            brocolli:'brocolli',
            brocolli_plural:'brocollis',
            
            pet_food:'pet food',
            pet_food_plural:'pet foods',
            pet_cutlery:'pet cutlery',
            pet_cutlery_plural:'pet cutleries',
            pet_name_tag:'pet name tag',
            pet_name_tag_plural:'pet name tags',
            pet_first_aid_kit:'pet first aid kit',
            pet_first_aid_kit_plural:'pet first aid kits',
            pet_bed:'pet bed',
            pet_bed_plural:'pet beds',
            pet_treat:'pet treat',
            pet_treat_plural:'pet treats',
            pet_toy:'pet toy',
            pet_toy_plural:'pet toys',
            pet_brush:'pet brush',
            pet_brush_plural:'pet brushes',
            pet_toothbrush:'pet toothbrush',
            pet_toothbrush_plural:'pet toothbrushes',
            pet_nail_trimmer:'pet nail trimmer',
            pet_nail_trimmer_plural:'pet nail trimmers',
            poop_disposal:'poop disposal',
            poop_disposal_plural:'poop disposals',
            leash:'leash',
            leash_plural:'leashes',
            collar:'collar',
            collar_plural:'collars',
            
            dish_soap:'dish soap',
            dish_soap_plural:'dish soaps',
            sponge:'sponge',
            sponge_plural:'sponges',
            plastic_wrap:'plastic wrap',
            plastic_wrap_plural:'plastic wraps',
            aluminium_foil:'aluminium foil',
            aluminium_foil_plural:'aluminium foil',
            trash_bag:'trash bag',
            trash_bag_plural:'trash bags',
            carry_bag:'carry bag',
            carry_bag_plural:'carry bags',
            laundry_soap:'laundry soap',
            laundry_soap_plural:'laundry soaps',
            dryer_sheet:'dryer sheet',
            dryer_sheet_plural:'dryer sheets',
            bleach:'bleach',
            bleach_plural:'bleachs',
            fabric_softener:'fabric softener',
            fabric_softener_plural:'fabric softeners',
            lint_roller:'lint roller',
            lint_roller_plural:'lint rollers',
            toilet_paper:'toilet paper',
            toilet_paper_plural:'toilet papers',
            hand_soap:'hand soap',
            hand_soap_plural:'hand soaps',
            cleaning_liquid:'cleaning liquid',
            cleaning_liquid_plural:'cleaning liquids',
            glove:'glove',
            glove_plural:'gloves',
            battery:'battery',
            battery_plural:'batteries',
            tissue:'tissue',
            tissue_plural:'tissues',
            napkin:'tissue',
            napkin_plural:'tissues',
            light:'light',
            light_plural:'lights',
            bedsheet:'bedsheet',
            bedsheet_plural:'bedsheets',
            blanket:'blanket',
            blanket_plural:'blankets',
            air_freshener:'air freshener',
            air_freshener_plural:'air fresheners',
            spoon:'spoon',
            spoon_plural:'spoons',
            glass:'glass',
            glass_plural:'glasses',
            bowl:'bowl',
            bowl_plural:'bowls',
            fork:'fork',
            fork_plural:'forks',
            knife:'knife',
            knife_plural:'knives',
            cup:'cup',
            cup_plural:'cups',
            plate:'plate',
            plate_plural:'plates',
            blender:'blender',
            blender_plural:'blenders',
            peeler:'peeler',
            peeler_plural:'peelers',
            rolling_pin:'rolling pin',
            rolling_pin_plural:'rolling pins',
            cutting_board:'cutting board',
            cutting_board_plural:'cutting boards',
            garbage_bin:'garbage bin',
            garbage_bin_plural:'garbage bins',
            bucket:'bucket',
            bucket_plural:'buckets',
            pan:'pan',
            pan_plural:'pans',
            grater:'grater',
            grater_plural:'graters',
            whisk:'whisk',
            whisk_plural:'whisks',
            pen:'pen',
            pen_plural:'pens',
            pencil:'pencil',
            pencil_plural:'pencils',
            scissor:'scissor',
            scissor_plural:'scissors',
            lightbulb:'lightbulb',
            lightbulb_plural:'lightbulbs',
            tubelight:'tubelight',
            tubelight_plural:'tubelights',
            
            first_aid_kit:'first aid kit',
            first_aid_kit_plural:'first aid kits',
            disinfectant:'disinfectant',
            disinfectant_plural:'disinfectants',
            chyawanprash:'chyawanprash',
            chyawanprash_plural:'chyawanprash',
            medication:'medication',
            medication_plural:'medications',
            sanitizer:'sanitizer',
            sanitizer_plural:'sanitizers',
            health_drink:'health drink',
            health_drink_plural:'health drinks',
            health_supplement:'health supplement',
            health_supplement_plural:'health supplements',
            saline:'saline',
            saline_plural:'salines',
            band_aid:'band aid',
            band_aid_plural:'band aids',
            cleaning_alcohol:'cleaning alcohol',
            cleaning_alcohol_plural:'cleaning alcohols',
            painkiller:'painkiller',
            painkiller_plural:'painkillers',
            antacid:'antacid',
            antacid_plural:'antacids',
            
            frozen_pea:'frozen pea',
            frozen_pea_plural:'frozen peas',
            ice_cream:'ice cream',
            ice_cream_plural:'ice creams',
            frozen_edamame:'frozen edamame',
            frozen_edamame_plural:'frozen edamames',
            frozen_good:'frozen good',
            frozen_good_plural:'frozen goods',
            frozen_bacon:'frozen bacon',
            frozen_bacon_plural:'frozen bacons',
            frozen_chicken:'frozen chicken',
            frozen_chicken_plural:'frozen chickens',
            soup:'soup',
            soup_plural:'soups',
            pizza:'pizza',
            pizza_plural:'pizzas',
            frozen_sausage:'frozen sausage',
            frozen_sausage_plural:'frozen sausages',
            frozen_fish:'frozen fish',
            frozen_fish_plural:'frozen fishes',
            
            flour:'flour',
            flour_plural:'flours',
            baking_chocolate:'baking chocolate',
            baking_chocolate_plural:'baking chocolates',
            baking_powder:'baking powder',
            baking_powder_plural:'baking powders',
            chocolate_chip:'chocolate chip',
            chocolate_chip_plural:'chocolate chips',
            baking_soda:'baking soda',
            baking_soda_plural:'baking sodas',
            brown_sugar:'brown sugar',
            brown_sugar_plural:'brown sugars',
            vanilla_extract:'vanilla extract',
            vanilla_extract_plural:'vanilla extracts',
            jam:'jam',
            jam_plural:'jams',
            cocoa_powder:'cocoa powder',
            cocoa_powder_plural:'cocoa powders',
            tea_powder:'tea powder',
            tea_powder_plural:'tea powders',
            cinnamon:'cinnamon',
            cinnamon_plural:'cinnamons',
            egg:'egg',
            egg_plural:'eggs',
            yeast:'yeast',
            yeast_plural:'yeasts',
            sugar:'sugar',
            sugar_plural:'sugars',
            fruit_jam:'fruit jam',
            fruit_jam_plural:'fruit jam',
            mixed_jam:'mixed jam',
            mixed_jam_plural:'mixed jams',
            
            wheat:'wheat',
            wheat_plural:'wheats',
            oat:'oat',
            oat_plural:'oats',
            barley:'barley',
            barley_plural:'barley',
            quinoa:'quinoa',
            quinoa_plural:'quinoas',
            millet:'millet',
            millet_plural:'millets',
            rye:'rye',
            rye_plural:'ryes',
            sorghum:'sorghum',
            sorghum_plural:'sorghums',
            moong_dal:'moong dal',
            moong_dal_plural:'moong dals',
            lentil:'lentil',
            lentil_plural:'lentils',
            toor_dal:'toor dal',
            toor_dal_plural:'toor dals',
            kidney_bean:'kidney bean',
            kidney_bean_plural:'kidney beans',
            split_black_lentil:'split black lentil',
            split_black_lentil_plural:'split black lentils',
            chick_pea:'chick pea',
            chick_pea_plural:'chick peas',
            chwali_dal:'chawli dal',
            chwali_dal_plural:'chawli dal',
            moth_dal:'moth dal',
            moth_dal_plural:'moth dal',
            
            deodrant:'deodrant',
            deodrant_plural:'deodrants',
            makeup:'makeup',
            makeup_plural:'makeups',
            toothbrush:'toothbrush',
            toothbrush_plural:'toothbrushes',
            toothpaste:'toothpaste',
            toothpaste_plural:'toothpastes',
            mouthwash:'mouthwash',
            mouthwash_plural:'mouthwashes',
            floss:'floss',
            floss_plural:'flosses',
            face_wash:'face wash',
            face_wash_plural:'face wash',
            body_wash:'body wash',
            body_wash_plural:'body wash',
            lotion:'lotion',
            lotion_plural:'lotions',
            towel:'towel',
            towel_plural:'towels',
            soap:'soap',
            soap_plural:'soaps',
            shampoo:'shampoo',
            shampoo_plural:'shampoos',
            conditioner:'conditioner',
            conditioner_plural:'conditioners',
            cotton_swab:'cotton swab',
            cotton_swab_plural:'cotton swabs',
            loofah:'loofah',
            loofah_plural:'loofahs',
            moisturizer:'moisturizer',
            moisturizer_plural:'moisturizers',
            shaving_cream:'shaving cream',
            shaving_cream_plural:'shaving creams',
            razor:'razor',
            razor_plural:'razors',
            comb:'comb',
            comb_plural:'combs',
            toothpick:'toothpick',
            toothpick_plural:'toothpicks',
            aftershave:'aftershave',
            aftershave_plural:'aftershaves',
            face_serum:'face serum',
            face_serum_plural:'face serums',
            body_serum:'body serum',
            body_serum_plural:'body serums',
            face_lotion:'face lotion',
            face_lotion_plural:'face lotions',
            hand_lotion:'hand lotion',
            hand_lotion_plural:'hand lotions',
            serum:'serum',
            body_lotion:'body lotion',
            body_lotion_plural:'body lotions',
            serum_plural:'serums',
            
            tea:'tea',
            tea_plural:'teas',
            coffee:'coffee',
            coffee_plural:'coffees',
            fruit_juice:'fruit juice',
            fruit_juice_plural:'fruit juices',
            energy_drink:'energy drink',
            energy_drink_plural:'energy drinks',
            soft_drink:'soft drink',
            soft_drink_plural:'soft drinks',
            soda:'soda',
            soda_plural:'sodas',
            water:'water',
            water_plural:'water',
            wine:'wine',
            wine_plural:'wines',
            red_wine:'red wine',
            red_wine_plural:'red wines',
            white_wine:'white wine',
            white_wine_plural:'white wines',
            
            papad:'papad',
            papad_plural:'papad',
            namkeen:'namkeen',
            namkeen_plural:'namkeen',
            chip:'chip',
            chip_plural:'chips',
            popcorn:'popcorn',
            popcorn_plural:'popcorns',
            cracker:'cracker',
            cracker_plural:'crackers',
            pretzel:'pretzel',
            pretzel_plural:'pretzels',
            
            carom_seed:'carom seed',
            carom_seed_plural:'carom seeds',
            hing_spice:'hing spice',
            hing_spice_plural:'hing spices',
            black_salt:'black salt',
            black_salt_plural:'black salts',
            cardamom_powder:'cardamom powder',
            cardamom_powder_plural:'cardamom powders',
            red_chili_powder:'red chili powder',
            red_chili_powder_plural:'red chili powders',
            coriander_powder:'coriander powder',
            coriander_powder_plural:'coriander powders',
            garam_masala:'garam masala',
            garam_masala_plural:'garam masala',
            cumin:'cumin',
            cumin_plural:'cumins',
            turmeric:'turmeric',
            turmeric_plural:'turmerics',
            chutney:'chutney',
            chutney_plural:'chutneys',
            raita:'raita',
            raita_plural:'raitas',
            sweet:'sweet',
            sweet_plural:'sweets',
            vinegar:'vinegar',
            vinegar_plural:'vinegars',
            schezwan:'schezwan',
            schezwan_plural:'schezwans',
            soya_chunk:'soya chunk',
            soya_chunk_plural:'soya chunks',
            green_chili_sauce:'green chili sauce',
            green_chili_sauce_plural:'green chili sauces',
            soy_sauce:'soy sauce',
            soy_sauce_plural:'soy sauces',
            mayonnaise:'mayonnaise',
            mayonnaise_plural:'mayonnaises',
            pasta_sauce:'pasta sauce',
            pasta_sauce_plural:'pasta sauces',
            tomato_ketchup:'tomato ketchup',
            tomato_ketchup_plural:'tomato ketchup',
            nutella:'nutella',
            nutella_plural:'nutella',
            ghee:'ghee',
            ghee_plural:'ghee',
            oil:'oil',
            oil_plural:'oils',
            oregano:'oregano',
            oregano_plural:'oreganos',
            red_chili_sauce:'red chili sauce',
            red_chili_sauce_plural:'red chili sauces',
            black_cumin:'black cumin',
            black_cumin_plural:'black cumins',
            salt:'salt',
            salt_plural:'salts',
            
            baby_food:'baby food',
            baby_food_plural:'baby foods',
            diaper:'diaper',
            diaper_plural:'diapers',
            wet_wipe:'wet wipe',
            wet_wipe_plural:'wet wipes',
            baby_lotion:'baby lotion',
            baby_lotion_plural:'baby lotions',
            baby_powder:'baby powder',
            baby_powder_plural:'baby powders',
            
            salami:'salami',
            salami_plural:'salamis',
            ham:'ham',
            ham_plural:'hams',
            turkey:'turkey',
            turkey_plural:'turkeys',
            
            shrimp:'shrimp',
            shrimp_plural:'shrimps',
            fish:'fish',
            fish_plural:'fishes',
            crab:'crab',
            crab_plural:'crabs',
            cod:'cod',
            cod_plural:'cods',
            tuna:'tuna',
            tuna_plural:'tunas',
            salmon:'salmon',
            salmon_plural:'salmons',
            octopus:'octopus',
            octopus_plural:'octopuses',
            clam:'clam',
            clam_plural:'clams',
            oyster:'oyster',
            oyster_plural:'oysters',
            prawn:'prawn',
            prawn_plural:'prawns',
            
            chicken:'chicken',
            chicken_plural:'chickens',
            beef:'beef',
            beef_plural:'beefs',
            pork:'pork',
            pork_plural:'porks',
            sausage:'sausage',
            sausage_plural:'sausages',
            bacon:'bacon',
            bacon_plural:'bacons',
            steak:'steak',
            steak_plural:'steaks',
            
            milk:'milk',
            milk_plural:'milk',
            butter:'butter',
            butter_plural:'butter',
            cream_cheese:'cream cheese',
            cream_cheese_plural:'cream cheeses',
            yogurt:'yogurt',
            yogurt_plural:'yogurt',
            cheese:'cheese',
            cheese_plural:'cheeses',
            sourmilk:'sourmilk',
            sourmilk_plural:'sourmilks',
            cottage_cheese:'cottage cheese',
            cottage_cheese_plural:'cottage cheeses',
            
            white_bread:'white bread',
            white_bread_plural:'white breads',
            bread:'bread',
            bread_plural:'breads',
            bun:'bun',
            bun_plural:'buns',
            whole_wheat_bread:'whole wheat bread',
            whole_wheat_bread_plural:'whole wheat breads',
            brown_bread:'brown bread',
            brown_bread_plural:'brown breads',
            cake:'cake',
            cake_plural:'cakes',
            pastry:'pastry',
            pastry_plural:'pastries',
            muffin:'muffin',
            muffin_plural:'muffins',
            biscuit:'biscuit',
            biscuit_plural:'biscuits',
            cookie:'cookie',
            cookie_plural:'cookies',
            
            linguini:'linguini',
            linguini_plural:'linguinis',
            penne:'penne',
            penne_plural:'pennes',
            fettuccine:'fettuccine',
            fettuccine_plural:'fettuccines',
            tortellini:'tortellini',
            tortellini_plural:'tortellinis',
            tagliatelle:'tagliatelle',
            tagliatelle_plural:'tagliatelles',
            macaroni:'macaroni',
            macaroni_plural:'macaronis',
            ravioli:'ravioli',
            ravioli_plural:'raviolis',
            rigatoni:'rigatoni',
            rigatoni_plural:'rigatonis',
            spaghetti:'spaghetti',
            spaghetti_plural:'spaghettis',
            lasagna:'lasagna',
            lasagna_plural:'lasagnas',
            
            basmati_rice:'basmati rice',
            basmati_rice_plural:'basmati rices',
            jasmine_rice:'jasmine rice',
            jasmine_rice_plural:'jasmine rices',
            brown_rice:'brown rice',
            brown_rice_plural:'brown rices',
            black_rice:'black rice',
            black_rice_plural:'black rices',
            red_rice:'red rice',
            red_rice_plural:'red rices',
            
            
            
            WELCOME_MSG: 'Hello. This is your grocery list. Would you like to add something or check what is in the cart?',
            WELCOME_MSG_PERSONALIZED: 'Hello {{- name}}. This is your grocery list. Would you like to add something or check what is in the cart?.',

            // GroceryShop Control
            GROCERY_SHOP_CONTROL_NON_UNDERSTANDING: 'I didn\'t catch that.',

            // Category Control
            CATEGORY_CONTROL_CATEGORY_IDS_VALIDATION_FAIL: 'Sorry, I don\'t know that product category.',
            CATEGORY_CONTROL_GENERAL_VALIDATION_FAIL: 'Sorry, it\'s not a valid choice.',
            CATEGORY_CONTROL_REQUEST_VALUE: 'What would you like?',
            CATEGORY_CONTROL_ALL_VALUE:'Hello! You can either ask me to check what is in your cart or you can ask me to add products for your purchase. Our categories include - dryfruits, seafoods, condiments, bakery, cereals, rices, pastas, pet care, baby care, household supplies, health care, personal care, frozen food, baking, beverage, snack, deli, meat, dairy, fruit and vegetables.',

            // Product Control
            PRODUCT_CONTROL_REQUEST_VALUE_WITH_CATEGORY: 'Some of our favorite {{category}} are {{favorites}}. Which would you like?',
            PRODUCT_CONTROL_REQUEST_VALUE_WITHOUT_CATEGORY: 'Which product would you like?',
            

            // ItemCount control
            ITEM_COUNT_CONTROL_REQUEST_VALUE_WITH_PRODUCT: 'How many {{itemText}}?',
            ITEM_COUNT_CONTROL_REQUEST_VALUE_WITHOUT_PRODUCT: 'How many?',
            ITEM_COUNT_CONTROL_INVALID_VALUE: 'Sorry I can only accept orders of one to fifty items.',
            ITEM_COUNT_CONTROL_CANCEL_VALUE: 'OK! {{itemText}} not added to the list!',

            // ShoppingCart control
            SHOPPING_CART_CONTROL_NON_UNDERSTANDING: 'I didn\'t get that.',
            SHOPPING_CART_CONTROL_ITEM_ADDED: 'Added {{itemText}}.',
            SHOPPING_CART_CONTROL_ADD_ANOTHER_ITEM: 'Would you like to add another item?',
            SHOPPING_CART_CONTROL_CART_IS_EMPTY: 'Your list is empty.',
            SHOPPING_CART_CONTROL_TELL_CART_CONTENT: 'Your list contains {{content}}.',
            SHOPPING_CART_CONTROL_SHOW_CART_APL_TITLE: 'Shopping list',
            SHOPPING_CART_CONTROL_SHOW_CART_APL_SUB_TITLE: 'Here are the items in your list',
            SHOPPING_CART_CONTROL_ITEM_REMOVED: 'I removed {{itemText}} from your list.',
        }
    },
};
